vim.cmd.highlight("clear")
vim.g.colors_name = "modus-cafe"

local c = {
  -- Modus-inspired: accessible contrast, restrained hues, no neon candy.
  base00 = "#11100f",
  base01 = "#1c1a18",
  base02 = "#2b2926",
  base03 = "#56514b",
  base04 = "#8d8780",
  base05 = "#d5d0c8",
  base06 = "#e2ddd5",
  base07 = "#f2eee7",
  base08 = "#ff8059",
  base09 = "#ef9f76",
  base0A = "#d0bc7a",
  base0B = "#9fc87b",
  base0C = "#70c0ba",
  base0D = "#79a8ff",
  base0E = "#d5b1ff",
  base0F = "#c6a15b",
}

local hl = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

hl("Normal", { fg = c.base05, bg = c.base00 })
hl("NormalFloat", { fg = c.base05, bg = c.base01 })
hl("NormalNC", { fg = c.base05, bg = c.base00 })
hl("ColorColumn", { bg = c.base01 })
hl("Conceal", { fg = c.base04, bg = "NONE" })
hl("Cursor", { fg = c.base00, bg = c.base05 })
hl("lCursor", { fg = c.base00, bg = c.base05 })
hl("CursorIM", { fg = c.base00, bg = c.base05 })
hl("CursorColumn", { bg = c.base01 })
hl("CursorLine", { bg = c.base01 })
hl("Directory", { fg = c.base0D })
hl("DiffAdd", { fg = c.base0B, bg = c.base01 })
hl("DiffChange", { fg = c.base0A, bg = c.base01 })
hl("DiffDelete", { fg = c.base08, bg = c.base01 })
hl("DiffText", { fg = c.base0D, bg = c.base01 })
hl("EndOfBuffer", { fg = c.base00 })
hl("ErrorMsg", { fg = c.base08 })
hl("VertSplit", { fg = c.base02 })
hl("WinSeparator", { fg = c.base02 })
hl("Folded", { fg = c.base04, bg = c.base01 })
hl("FoldColumn", { fg = c.base04, bg = "NONE" })
hl("SignColumn", { bg = "NONE" })
hl("IncSearch", { fg = c.base00, bg = c.base0A })
hl("Search", { fg = c.base00, bg = c.base0A })
hl("CurSearch", { fg = c.base00, bg = c.base0A })
hl("Substitute", { fg = c.base00, bg = c.base0A })
hl("LineNr", { fg = c.base03, bg = "NONE" })
hl("LineNrAbove", { fg = c.base03, bg = "NONE" })
hl("LineNrBelow", { fg = c.base03, bg = "NONE" })
hl("CursorLineNr", { fg = c.base05, bg = c.base01 })
hl("CursorLineSign", { bg = c.base01 })
hl("MatchParen", { fg = c.base0D, bg = c.base02, bold = true })
hl("ModeMsg", { fg = c.base05 })
hl("MsgArea", { fg = c.base05 })
hl("MsgSeparator", { fg = c.base04 })
hl("MoreMsg", { fg = c.base0D })
hl("NonText", { fg = c.base03 })
hl("Whitespace", { fg = c.base03 })
hl("Pmenu", { fg = c.base05, bg = c.base01 })
hl("PmenuSel", { fg = c.base07, bg = c.base02 })
hl("PmenuSbar", { bg = c.base01 })
hl("PmenuThumb", { bg = c.base04 })
hl("Question", { fg = c.base0D })
hl("QuickFixLine", { fg = c.base00, bg = c.base0D })
hl("SpecialKey", { fg = c.base03 })
hl("SpellBad", { sp = c.base08, undercurl = true })
hl("SpellCap", { sp = c.base0D, undercurl = true })
hl("SpellLocal", { sp = c.base0C, undercurl = true })
hl("SpellRare", { sp = c.base0E, undercurl = true })
hl("StatusLine", { fg = c.base05, bg = c.base02 })
hl("StatusLineNC", { fg = c.base04, bg = c.base01 })
hl("TabLine", { fg = c.base04, bg = c.base01 })
hl("TabLineFill", { bg = c.base01 })
hl("TabLineSel", { fg = c.base07, bg = c.base02 })
hl("Title", { fg = c.base0D, bold = true })
hl("Visual", { bg = c.base02 })
hl("VisualNOS", { bg = c.base02 })
hl("WarningMsg", { fg = c.base0A })
hl("WildMenu", { fg = c.base00, bg = c.base0D })
hl("WinBar", { fg = c.base04, bg = "NONE" })
hl("WinBarNC", { fg = c.base04, bg = "NONE" })
hl("Boolean", { fg = c.base09 })
hl("Character", { fg = c.base08 })
hl("Comment", { fg = c.base04, italic = true })
hl("Conditional", { fg = c.base0E })
hl("Constant", { fg = c.base09 })
hl("Debug", { fg = c.base08 })
hl("Define", { fg = c.base0E })
hl("Delimiter", { fg = c.base05 })
hl("Error", { fg = c.base08 })
hl("Exception", { fg = c.base0E })
hl("Float", { fg = c.base09 })
hl("Function", { fg = c.base0D })
hl("Identifier", { fg = c.base05 })
hl("Include", { fg = c.base0E })
hl("Keyword", { fg = c.base0E })
hl("Label", { fg = c.base08 })
hl("Macro", { fg = c.base08 })
hl("Number", { fg = c.base09 })
hl("Operator", { fg = c.base05 })
hl("PreProc", { fg = c.base0E })
hl("Repeat", { fg = c.base0E })
hl("Special", { fg = c.base0C })
hl("SpecialChar", { fg = c.base08 })
hl("SpecialComment", { fg = c.base04 })
hl("Statement", { fg = c.base0E })
hl("StorageClass", { fg = c.base0E })
hl("String", { fg = c.base0B })
hl("Structure", { fg = c.base0E })
hl("Tag", { fg = c.base08 })
hl("Todo", { fg = c.base0A, bg = c.base01, bold = true })
hl("Type", { fg = c.base0A })
hl("Typedef", { fg = c.base0A })
hl("Underlined", { underline = true })

hl("@comment", { fg = c.base04, italic = true })
hl("@comment.documentation", { fg = c.base04, italic = true })
hl("@constant", { fg = c.base09 })
hl("@constant.builtin", { fg = c.base09 })
hl("@constant.macro", { fg = c.base08 })
hl("@constructor", { fg = c.base0C })
hl("@function", { fg = c.base0D })
hl("@function.builtin", { fg = c.base0D })
hl("@function.call", { fg = c.base0D })
hl("@function.macro", { fg = c.base0D })
hl("@function.method", { fg = c.base0D })
hl("@function.method.call", { fg = c.base0D })
hl("@keyword", { fg = c.base0E })
hl("@keyword.function", { fg = c.base0E })
hl("@keyword.operator", { fg = c.base0E })
hl("@keyword.return", { fg = c.base0E })
hl("@label", { fg = c.base08 })
hl("@method", { fg = c.base0D })
hl("@method.call", { fg = c.base0D })
hl("@namespace", { fg = c.base08 })
hl("@number", { fg = c.base09 })
hl("@number.float", { fg = c.base09 })
hl("@operator", { fg = c.base05 })
hl("@parameter", { fg = c.base05 })
hl("@property", { fg = c.base0C })
hl("@punctuation", { fg = c.base04 })
hl("@punctuation.bracket", { fg = c.base05 })
hl("@punctuation.delimiter", { fg = c.base05 })
hl("@punctuation.special", { fg = c.base05 })
hl("@string", { fg = c.base0B })
hl("@string.documentation", { fg = c.base0B })
hl("@string.escape", { fg = c.base0C })
hl("@string.regexp", { fg = c.base0C })
hl("@string.special", { fg = c.base0C })
hl("@tag", { fg = c.base08 })
hl("@tag.attribute", { fg = c.base0A })
hl("@tag.delimiter", { fg = c.base04 })
hl("@text", { fg = c.base05 })
hl("@text.danger", { fg = c.base08 })
hl("@text.emphasis", { fg = c.base05, italic = true })
hl("@text.environment", { fg = c.base0E })
hl("@text.environment.name", { fg = c.base0E })
hl("@text.literal", { fg = c.base0B })
hl("@text.math", { fg = c.base0C })
hl("@text.note", { fg = c.base04 })
hl("@text.reference", { fg = c.base0D })
hl("@text.strikethrough", { fg = c.base04, strikethrough = true })
hl("@text.strong", { bold = true })
hl("@text.title", { fg = c.base0D, bold = true })
hl("@text.todo", { fg = c.base0A, bold = true })
hl("@text.underline", { underline = true })
hl("@text.uri", { fg = c.base0D, underline = true })
hl("@text.warning", { fg = c.base0A })
hl("@type", { fg = c.base0A })
hl("@type.builtin", { fg = c.base0A })
hl("@type.definition", { fg = c.base0A })
hl("@type.qualifier", { fg = c.base0E })
hl("@variable", { fg = c.base05 })
hl("@variable.builtin", { fg = c.base08 })
hl("@variable.member", { fg = c.base05 })
hl("@variable.parameter", { fg = c.base05 })

hl("DiagnosticError", { fg = c.base08 })
hl("DiagnosticWarn", { fg = c.base0A })
hl("DiagnosticInfo", { fg = c.base0D })
hl("DiagnosticHint", { fg = c.base0C })
hl("DiagnosticOk", { fg = c.base0B })
hl("DiagnosticUnderlineError", { sp = c.base08, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = c.base0A, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = c.base0D, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = c.base0C, undercurl = true })
hl("DiagnosticUnderlineOk", { sp = c.base0B, undercurl = true })
hl("DiagnosticSignError", { fg = c.base08 })
hl("DiagnosticSignWarn", { fg = c.base0A })
hl("DiagnosticSignInfo", { fg = c.base0D })
hl("DiagnosticSignHint", { fg = c.base0C })

hl("LspReferenceText", { bg = c.base02 })
hl("LspReferenceRead", { bg = c.base02 })
hl("LspReferenceWrite", { bg = c.base02 })
